### ISSUE TITLE
Setup Github pages

### ISSUE THREAD

**Issue by ar-x** [turtlecoin/turtlecoin-api-docs-site#1]
Go here: https://github.com/turtlecoin/turtlecoin-api-docs-site/settings, and do this, and then let me know.

<img width="758" alt="todo" src="https://user-images.githubusercontent.com/37969038/41082356-e0e77cde-69e2-11e8-884a-0d5a75bc9eb8.png">

**Comment by RocksteadyTC** [comment]
this is done now
